apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: minio-noprod
  namespace: openshift-gitops
spec:
  generators:
  # - clusterDecisionResource:
  #     configMapRef: acm-placement
  #     labelSelector:
  #       matchLabels:
  #         cluster.open-cluster-management.io/placement: gitops-noprod-clusters
  #     requeueAfterSeconds: 180
  - list:
      elements:
      - name: noprod
        server: https://kubernetes.default.svc
  template:
    metadata:
      name: minio-{{name}}
    spec:
      destination:
        namespace: minio
        server: '{{server}}'
      ignoreDifferences:
      - group: operators.coreos.com
        jsonPointers:
        - /spec/installPlanApproval
        - /spec/startingCSV
        kind: Subscription
      project: 3scale-noprod
      source:
        path: minio/overlays/default
        repoURL: https://github.com/mcaballol/poc-3scale-gitops.git
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
          selfHeal: false