kind: Secret
apiVersion: v1
metadata:
  name: minio
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

stringData:
  # change the username and password to your own values.
  # ensure that the user is at least 3 characters long and the password at least 8
  minio_root_user: minio
  minio_root_password: minio123
